esphome:
  name: ce2727a-esp32

esp32:
  board: esp32dev
  framework:
    type: arduino

# esp8266:
#   board: nodemcuv2

logger:
  level: INFO
      
external_components:
  source: 
    type: local
    path: my_components
  components: [ce2727a]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_broker

api:
  password: !secret api_password

ota:
  password: !secret ota_password
  
output:
  - platform: gpio
    id: led
    pin: GPIO04
    inverted: true
 
light:
  - platform: binary
    id: in_led
    output: led
    name: Test Lamp


uart:
  id: rs485
  rx_pin: 16
  tx_pin: 17
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  stop_bits: 1
  rx_buffer_size: 256
  
ce2727a:
  flow_control_pin: 15
  receive_timeout: 500ms

text_sensor:
  - platform: ce2727a
    electricity_tariff: 
      name: "Electricity Tariff"

sensor:
  - platform: ce2727a
    active_power: 
      name: "Active Power"
    energy_total:
      name: "Energy Consumed Total"  
    energy_t1:
      name: "Energy Consumed T1"
    energy_t2:
      name: "Energy Consumed T2"
    energy_t3:
      name: "Energy Consumed T3"
    energy_t4:
      name: "Energy Consumed T4"

#  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
#    name: "WiFi Signal dB"
#    id: wifi_signal_db
#    update_interval: 60s
#    entity_category: "diagnostic"
#
#  - platform: copy # Reports the WiFi signal strength in %
#    source_id: wifi_signal_db
#    name: "WiFi Signal Percent"
#    filters:
#      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
#    unit_of_measurement: "Signal %"
#    entity_category: "diagnostic"

  - platform: uptime
    name: Uptime Sensor
