esphome:
  name: ce2727a-8266

esp8266:
  board: nodemcuv2

logger:
  level: INFO
      
external_components:
  source: github://latonita/esphome-ce2727a-meter@main
  components: [ce2727a]

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min
  power_save_mode: NONE

mqtt:
  broker: !secret mqtt_broker
  discovery: False

api:
  password: !secret api_password

ota:
  password: !secret ota_password
  
output:
  - platform: gpio
    id: led
    pin: GPIO04
    inverted: true
 
light:
  - platform: binary
    id: in_led
    output: led
    name: Test LED

web_server:
  port: 80
  auth:
    username: !secret web_user
    password: !secret web_password

uart:
  id: rs485
  rx_pin: 5
  tx_pin: 4
  baud_rate: 9600
  data_bits: 8
  parity: EVEN
  stop_bits: 1
  rx_buffer_size: 256
  
ce2727a:
  flow_control_pin: 15
  receive_timeout: 300ms

text_sensor:
  - platform: ce2727a
    electricity_tariff: 
      name: "Active tariff"
    date:
      name: "Date"
    time:
      name: "Time"
    network_address:
      name: "Network address"
    serial_nr: 
      name: "Serial number"
    state: 
      name: "Component state"
      
sensor:
  - platform: ce2727a
    active_power: 
      name: "Active power"
    energy_total:
      name: "Energy consumed total"  
    energy_t1:
      name: "Energy consumed tariff 1"
    energy_t2:
      name: "Energy consumed tariff 2"
    energy_t3:
      name: "Energy consumed tariff 3"
    energy_t4:
      name: "Energy consumed tariff 4"

#  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
#    name: "WiFi Signal dB"
#    id: wifi_signal_db
#    update_interval: 60s
#    entity_category: "diagnostic"
#
#  - platform: copy # Reports the WiFi signal strength in %
#    source_id: wifi_signal_db
#    name: "WiFi Signal Percent"
#    filters:
#      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
#    unit_of_measurement: "Signal %"
#    entity_category: "diagnostic"

  - platform: uptime
    name: Uptime sensor
